#!/usr/bin/with-contenv bash

# make folders
mkdir -p \
	/config/oscam

# copy config
[[ ! -e /config/oscam/oscam.conf ]] && \
	cp /defaults/oscam.conf /config/oscam/oscam.conf

# permissions
chown -R abc:abc \
	/config
