#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# make folders
mkdir -p \
	/config/oscam

# copy config
if [[ ! -e /config/oscam/oscam.conf ]]; then
	cp /defaults/oscam.conf /config/oscam/oscam.conf
fi

# permissions
lsiown -R abc:abc \
	/config
