#!/usr/bin/with-contenv bash

# Check if /config/oscam/oscam.conf exists
[[ ! -e /config/oscam/oscam.conf ]] && \
	(mkdir -p /config/oscam && cp /defaults/oscam.conf /config/oscam/oscam.conf)

# permissions
chown -R abc:abc \
	/config
